---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(scales)
```


```{r}
ecoregion_pop_trends <- read_csv("ecoregion_pop_trends.csv")
```


```{r fig.height=2.5, fig.width=4}
ecoregion_pop_trends %>% 
  filter(ecoregion == "SOPR") %>% 
  ggplot(data = ., mapping = aes(x = year, y = population_size)) +
  theme_bw() +
  geom_point() +
  geom_errorbar(aes(ymin = lcl_90, ymax = ucl_90), width = 0.2) +
  xlab("Year") +
  ylab("Estimated population size") +
  ggtitle("Sand Shinnery Oak Prairie") +
  theme(plot.title = element_text(size=12)) +
  scale_y_continuous(labels = label_number(scale_cut = cut_short_scale()), limits = c(0, 15000)) +
  scale_x_continuous(breaks=seq(2012, 2022, 2))

ggsave("SOPR_pop_trend.tiff", height = 2.5, width = 4)
```


```{r}
ecoregion_pop_trends %>% 
  filter(ecoregion == "SSPR") %>% 
  ggplot(data = ., mapping = aes(x = year, y = population_size)) +
  theme_bw() +
  geom_point() +
  geom_errorbar(aes(ymin = lcl_90, ymax = ucl_90), width = 0.2) +
  xlab("Year") +
  ylab("Estimated population size") +
  ggtitle("Sand Sagebrush Prairie") +
  theme(plot.title = element_text(size=12)) +
  scale_y_continuous(labels = label_number(scale_cut = cut_short_scale()), limits = c(0, 15000)) +
  scale_x_continuous(breaks=seq(2012, 2022, 2))


ggsave("SSPR_pop_trend.tiff", height = 2.5, width = 4)
```


```{r}
ecoregion_pop_trends %>% 
  filter(ecoregion == "MGPR") %>% 
  ggplot(data = ., mapping = aes(x = year, y = population_size)) +
  theme_bw() +
  geom_point() +
  geom_errorbar(aes(ymin = lcl_90, ymax = ucl_90), width = 0.2) +
  xlab("Year") +
  ylab("Estimated population size") +
  ggtitle("Mixed-grass Prairie") +
  theme(plot.title = element_text(size=12)) +
  scale_y_continuous(labels = label_number(scale_cut = cut_short_scale()), limits = c(0, 15000)) +
  scale_x_continuous(breaks=seq(2012, 2022, 2))

ggsave("MGPR_pop_trend.tiff", height = 2.5, width = 4)
```


```{r fig.height=2.5, fig.width=4}
ecoregion_pop_trends %>% 
  filter(ecoregion == "SGPR") %>% 
  ggplot(data = ., mapping = aes(x = year, y = population_size)) +
  theme_bw() +
  geom_point() +
  geom_errorbar(aes(ymin = lcl_90, ymax = ucl_90), width = 0.2) +
  xlab("Year") +
  ylab("Estimated population size") +
  ggtitle("Short-grass Prairie/CRP Mosaic") +
  theme(plot.title = element_text(size=12)) +
  scale_y_continuous(labels = label_number(scale_cut = cut_short_scale()), limits = c(0, 40000)) +
  scale_x_continuous(breaks=seq(2012, 2022, 2))

ggsave("SGPR_pop_trend.tiff", height = 2.5, width = 4)
```